### ISSUE TITLE
Cart  isn't cleared after successful order placement

### ISSUE THREAD

**Issue by vmalyk** [sveawebpay/nwt-magento2-checkout#34]
**Pre-conditions:**

Svea Checkout - 1.2.8
Magento Open Source 2.3.5-p2
PHP 7.3

**Steps to reproduce:**
2. Add product to cart and proceed to checkout
3. Fill in all details and proceed to payment
4. Finish payment 
5. From order success page click 'Continue shopping'

**Expected result:**
Redirected to Home Page. Cart cleared.

**Actual result:**
Cart still shows items number.

**Comment by lrvipul** [comment]
Hi
I am also facing same problem, After successful payment from SVEA checkout method, minicart is not getting cleared.
I  applied 2 solution for that
1) update the minicart using section update after order success
2) customer data reload on success page

**Comment by martinSternelius** [comment]
This will be fixed in the upcoming version 1.3.3

**Comment by martinSternelius** [comment]
Now fixed latest release 1.3.4!
