### ISSUE TITLE
Can't view none SVEA orders in admin

### ISSUE THREAD

**Issue by andrewsurrey** [sveawebpay/nwt-magento2-checkout#61]
There's an issue whereby you can't view old orders in the admin, this was for version 1.3.13

This version seems to have been removed from the repository now, which can cause issues for people who have already installed it.

There's a simple patch to fix that:

    diff --git a/ViewModel/Adminhtml/Order/View/Shipping.php b/ViewModel/Adminhtml/Order/View/Shipping.php
    --- a/ViewModel/Adminhtml/Order/View/Shipping.php
    +++ b/ViewModel/Adminhtml/Order/View/Shipping.php
    @@ -39,7 +39,7 @@
         {
             if (!$this->locationObj) {
                 $shipInfo = $this->sveaShippingInfo->getFromOrder($order);
    -            $locationData = $shipInfo->getLocation();
    +            $locationData = $shipInfo?->getLocation() ?? [];
                 $this->locationObj = $this->dataObjectFactory->create()->setData($locationData);
             }
            return $this->locationObj;

**Comment by martinSternelius** [comment]
This will be fixed in the next release. Apologies for the inconvenience.

**Comment by martinSternelius** [comment]
Should be fixed now in the release we just published.
