### ISSUE TITLE
Issue with emails

### ISSUE THREAD

**Issue by andrewsurrey** [sveawebpay/nwt-magento2-checkout#62]
main.CRITICAL: Error: Call to a member function getLocation() on null in ..Svea/Checkout/Observer/EmailOrderSetTemplateVarsBefore.php:67

verison 1.3.13

fix:

`$locationData = $shipInfo?->getLocation() ?? [];`

**Comment by martinSternelius** [comment]
This will be fixed in the next release. Apologies for the inconvenience.

**Comment by martinSternelius** [comment]
Should be fixed now in the release we just published.
